services:
  eureka-server:
    build:
      context: ./eureka_server
    ports:
      - "8761:8761"

  config-server:
    build:
      context: ./config_server
    ports:
      - "8888:8888"

  customer-service:
    build:
      context: ./customer
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server

  inventory-service:
    build:
      context: ./inventory
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server

  order-service:
    build:
      context: ./order
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server

  product-service:
    build:
      context: ./product
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - config-server

  api-gateway-server:
    build:
      context: ./api_gateway
    ports:
      - "8080:8080"